### ISSUE TITLE
error: failed to run custom build command for `chromiumoxide_cdp v0.3.0`

### ISSUE THREAD

**Issue by dipa96** [dwisiswant0/ppfuzz#14] opened 2021-07-06 12:29 UTC
Hello folks, 

How i can fix this issue?
Regards :)

![immagine](https://user-images.githubusercontent.com/55739764/124599845-6ce66100-de66-11eb-938a-66039d610f1d.png)

**Comment by mattsse** [comment] 2021-07-06 12:34
that's probably a dupe of #10

**Closed** 2021-07-06 12:47 UTC
